import fs from 'node:fs';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
const file='/Users/tamchap/Dev/mh_media/tutorial-demo-builder-v2.html';
const html=fs.readFileSync(file,'utf8');
const scripts=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)];
const runtime=scripts.find(m=>m[2].includes('function deleteSelected()'))[2];
const window=new Window({url:'https://unit.test/',settings:{disableJavaScriptEvaluation:true,disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableComputedStyleRendering:false}});
window.document.write(html.replace(/<script\b(?![^>]*application\/json)[^>]*>[\s\S]*?<\/script>/gi,''));
const exports=['normalizeAnnotation','normalizeHotspot','normalizeState','currentSlide','renderToolbar','safeWordHtml','renderWordText','renderBody','captureWordFormatting','rememberWordSelection','applyWordStyles','toggleWordFormat','markupSvg','objectStyle','renderAnnotation','renderContentsPreviewAnnotation','renderHotspot','onClick','onChange','onInput','onKeyDown','selectedObject','addText','addMarkup','addMagnifierAnnotation','moveHotspot','buildExportHtml','applyExportFont','isVisibleForActiveHotspot','handleToolbarField','handleToolbarColor','normalizeMarkupKind','renderHotspotRow','renderHotspotDetail'];
let code=runtime.replace('    initializeApp();','');
code=code.replace('  })();',`window.audit={${exports.filter(n=>runtime.includes('function '+n+'(')).join(',')},get state(){return state},set state(v){state=v},get mode(){return MODE},setSelection(id,kind='annotation'){state.ui.selectedId=id;state.ui.selectedKind=kind},setup(){normalizeState();},quiet(){commit=(message)=>{recordUndoStep();};scheduleSave=()=>{};showToast=()=>{};},render(){root.innerHTML=renderToolbar(currentSlide(),selectedObject());},async build(mode){waitForExportFonts=async()=>{};render=()=>{};fitRenderedTextCardsToContent=()=>{};syncLiveEditableBeforeRender=()=>{};return buildExportHtml(mode);}};})();`);
window.eval(code);
const a=window.audit;a.setup();a.quiet();
const doc=window.document, root=doc.querySelector('#app');
const results=[];
function test(name,fn){try{fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});console.error(name,e.message);}}
const slide=a.currentSlide();slide.annotations=[];slide.hotspots=[];
function annotation(type,extra={}){const n=a.normalizeAnnotation({id:type+'-'+slide.annotations.length,type,...extra},slide.annotations.length,slide);slide.annotations.push(n);return n;}
function edit(item,html,binding=`annotation.text:${item.id}`){item.text=html.replace(/<[^>]+>/g,'');root.innerHTML=`<div contenteditable="true" data-bind="${binding}">${html}</div>`;const e=root.firstElementChild;e.addEventListener('input',()=>{item.text=e.textContent;a.captureWordFormatting(e);});return e;}
function select(e,start,end){const walker=doc.createTreeWalker(e,window.NodeFilter.SHOW_TEXT);const r=doc.createRange();let at=0,n,started=false;while((n=walker.nextNode())){if(!started&&start<=at+n.length){r.setStart(n,start-at);started=true;}if(started&&end<=at+n.length){r.setEnd(n,end-at);break;}at+=n.length;}const sel=window.getSelection();sel.removeAllRanges();sel.addRange(r);a.rememberWordSelection();}
for(const type of ['image','gif','shape','text','slide-intro','callout','markup','cover','blur','magnifier','clip-frame','link','video','audio']) test(type+' normalization/save roundtrip',()=>{const x=annotation(type,{url:'https://example.test/asset',textStyle:'hand',outerOutlineWidth:4,outerOutlineColor:'#ff74e9'});const y=a.normalizeAnnotation(JSON.parse(JSON.stringify(x)),0,slide);assert.equal(y.type,type);assert.equal(y.outerOutlineWidth,4);assert.equal(y.outerOutlineColor,'#ff74e9');});
test('toolbar renders 3 rows and all 68 artwork files',()=>{a.setSelection(null);a.render();assert.equal(root.querySelectorAll('.numbered-toolbar-row').length,3);const imgs=[...root.querySelectorAll('img.numbered-toolbar-art')];assert(imgs.length>=68);for(const img of imgs){assert(fs.existsSync('/Users/tamchap/Dev/mh_media/'+decodeURIComponent(img.getAttribute('src'))),img.src);}});
for(const type of ['image','gif','shape','text','slide-intro','callout','markup','cover','blur','magnifier','clip-frame','link','video','audio'])test(type+' toolbar applicability',()=>{a.setSelection(slide.annotations.find(x=>x.type===type).id);a.render();assert.equal(root.querySelectorAll('.numbered-toolbar-row').length,3);});
for(const type of ['image','gif','shape','text','slide-intro','callout','markup','cover','blur','magnifier','clip-frame','link','video','audio']) test(type+' annotation and contents renderer',()=>{const x=slide.annotations.find(a=>a.type===type);a.setSelection(null);assert(a.renderAnnotation(x).includes('annotation-'+type));assert(a.renderContentsPreviewAnnotation(x).length>0);});
for(const key of ['b','i','u'])test('Command-'+key+' selected-word toggle',()=>{const x=annotation('text');const e=edit(x,'one two three');select(e,4,7);a.onKeyDown({target:e,key,metaKey:true,preventDefault(){}});const out=e.innerHTML;assert(out.includes(key==='b'?'font-weight: 700':key==='i'?'font-style: italic':'text-decoration-line: underline'));a.onKeyDown({target:e,key,metaKey:true,preventDefault(){}});assert(e.innerHTML.includes(key==='b'?'font-weight: 400':key==='i'?'font-style: normal':'text-decoration-line: none'));assert.equal(e.textContent,'one two three');});
test('hotspot formatting moves with title and body',()=>{const h1=a.normalizeHotspot({id:'h1',title:'Custom one',autoTitle:false,body:'body',richText:{title:{text:'Custom one',html:'<b>Custom one</b>'}}},0,slide),h2=a.normalizeHotspot({id:'h2',title:'Custom two',autoTitle:false},1,slide);slide.hotspots=[h1,h2];a.moveHotspot('h1',1);assert.equal(slide.hotspots[1].richText.title.text,'Custom one');assert.equal(slide.hotspots[0].richText.title,undefined);});
test('sanitizer retains safe B/I/U and rejects scripts/events',()=>{const out=a.safeWordHtml('<b>bold</b><i>italics</i><u>underlined</u><script>alert(1)</script><img src=x onerror=bad()>');assert(out.includes('font-weight:700'));assert(out.includes('font-style:italic'));assert(out.includes('text-decoration-line:underline'));assert(!out.includes('script'));assert(!out.includes('onerror'));});
test('only selected word receives bold, retains adjacent text',()=>{const x=annotation('text');const e=edit(x,'one two three');select(e,4,7);a.applyWordStyles({'font-weight':'700'});assert.equal(e.textContent,'one two three');assert.equal(e.querySelector('[style*="700"]').textContent,'two');assert(a.renderWordText(x,'text').includes('700'));});
test('toggle off removes nested style without losing neighbours',()=>{const x=annotation('text');const e=edit(x,'one two three');select(e,4,7);a.applyWordStyles({'font-weight':'700','font-style':'italic'});a.applyWordStyles({'font-weight':'400'});assert(!e.innerHTML.includes('700'));assert(e.innerHTML.includes('italic'));assert.equal(e.textContent,'one two three');});
test('highlight and underline independent colors/thickness/offset survive reload',()=>{const x=annotation('text');const e=edit(x,'one two three');select(e,4,7);a.applyWordStyles({'color':'#ff0000','background-color':'#ffff00','text-decoration-line':'underline','text-decoration-color':'#0000ff','text-decoration-thickness':'3px','text-underline-offset':'4px'});const y=a.normalizeAnnotation(JSON.parse(JSON.stringify(x)),0,slide);const out=a.renderWordText(y,'text');assert(out.includes('text-decoration-thickness:3px'));assert(out.includes('background-color:'));assert(out.includes('text-underline-offset:4px'));});
test('main filled shape color uses fill, not stroke',()=>{const x=annotation('markup',{markup:'square-fill',fillColor:'#ff0000',markupColor:'#0000ff'});assert(a.markupSvg(x).includes('var(--markup-fill-color'));});
for(const kind of ['line-solid','line-dotted','arrow-solid','arrow-dotted','circle-solid','circle-dotted','circle-fill','circle-fill-solid','circle-fill-dashed','square-solid','square-dotted','square-fill','square-fill-solid','square-fill-dashed'])test(kind+' outer outline render',()=>{const x=annotation('markup',{markup:kind,outerOutlineWidth:3,outerOutlineColor:'#ff0000'});const svg=a.markupSvg(x);assert(svg.includes('feMorphology'));assert(svg.includes('#ff0000'));assert(svg.includes('SourceGraphic'));});
test('persistent title command creates one synchronized annotation',()=>{a.setSelection(null);root.innerHTML='<button data-action="persistent-slide-title">Title</button>';a.onClick({target:root.firstElementChild,preventDefault(){},stopPropagation(){}});const x=slide.annotations.find(x=>x.persistentSlideTitle);assert(x);assert.equal(x.text,slide.title);assert(a.isVisibleForActiveHotspot(x));root.innerHTML='<button data-action="persistent-slide-title">Title</button>';a.onClick({target:root.firstElementChild,preventDefault(){},stopPropagation(){}});assert.equal(slide.annotations.filter(x=>x.persistentSlideTitle).length,1);});
test('magnifier outline can turn off and back on',()=>{const x=slide.annotations.find(x=>x.type==='magnifier');a.setSelection(x.id);a.render();const input=root.querySelector('[data-toolbar-field="outerOutlineWidth"]');input.value='0';a.handleToolbarField(input,true);assert.equal(x.outlineEnabled,false);input.value='5';a.handleToolbarField(input,true);assert.equal(x.outlineEnabled,true);assert(a.objectStyle(x).includes('--object-outline-width:5px'));});
test('custom main color leaves raster image appearance unchanged',()=>{const x=slide.annotations.find(x=>x.type==='image');a.setSelection(x.id);a.render();a.rememberWordSelection.saved=null;const before=x.appearanceColor;a.handleToolbarColor('main','#ff0000');assert.equal(x.appearanceColor,before);});
test('cross-span partial formatting preserves outside ranges',()=>{const x=annotation('text');const e=edit(x,'<b>one two</b> three');select(e,4,10);a.applyWordStyles({'font-style':'italic'});assert.equal(e.textContent,'one two three');assert(e.innerHTML.includes('one '));assert(e.innerHTML.includes('ree'));});
test('legacy plain fills preserve their previous visible color',()=>{const x=a.normalizeAnnotation({type:'markup',markup:'square-fill',markupColor:'#123456',fillColor:'#ffffff'},0,slide);assert.equal(x.fillColor,'#123456');assert.equal(x.markupFillVersion,1);const y=a.normalizeAnnotation({...x,fillColor:'#ff0000'},0,slide);assert.equal(y.fillColor,'#ff0000');});
test('main color sets shared new text/shape defaults',()=>{a.setSelection(null);a.rememberWordSelection.saved=null;a.handleToolbarColor('main','#91a8ed');a.addText('regular');assert.equal(a.selectedObject().textColor,'#91a8ed');a.addMarkup('square-fill');assert.equal(a.selectedObject().fillColor,'#91a8ed');a.addMarkup('line-solid');assert.equal(a.selectedObject().markupColor,'#91a8ed');});
test('reset crop preserves corners and removes crop state',()=>{const x=slide.annotations.find(x=>x.type==='image');Object.assign(x,{cornerRadius:20,cropEnabled:true,cropWindow:{left:2,top:3,width:60,height:70},cropScale:2});a.setSelection(x.id);root.innerHTML='<button data-action="toolbar-reset-crop">Reset</button>';a.onClick({target:root.firstElementChild,preventDefault(){},stopPropagation(){}});assert.equal(x.cornerRadius,20);assert.equal(x.cropEnabled,false);assert.equal(x.cropWindow,null);});
test('word highlight excludes trailing selected whitespace',()=>{const x=annotation('text');const e=edit(x,'one two three');select(e,4,8);a.applyWordStyles({'background-color':'#ffff00'});assert.equal(e.querySelector('[style*="background-color"]').textContent,'two');assert.equal(e.textContent,'one two three');});
for(const style of ['regular','hand','impact-label','impact-label-reversed'])test(style+' family remains after inline emphasis and save/reload',()=>{a.addText(style);const x=a.selectedObject();const e=edit(x,'one two three');select(e,4,7);a.applyWordStyles({'font-weight':'700','font-style':'italic'});const y=a.normalizeAnnotation(JSON.parse(JSON.stringify(x)),0,slide);assert.equal(y.textStyle,style);const rendered=a.renderAnnotation(y);assert(rendered.includes('data-text-style="'+style+'"'));assert(rendered.includes('font-weight:700'));});
test('font data contains all five faces and true italic',()=>{const css=doc.querySelector('#portable-export-fonts').textContent;assert.equal((css.match(/@font-face/g)||[]).length,5);assert(css.includes('font-style:italic'));assert.equal((css.match(/data:font/g)||[]).length,5);});
for(const mode of ['demo','tutorial']){try{const out=await a.build(mode);assert(out.html.includes('data-mode="player"'));assert(out.html.includes('portable-export-fonts'));assert(out.html.includes('text-decoration-thickness'));assert.equal(out.isDemoExport,mode==='demo');fs.writeFileSync('/private/tmp/mh-toolbar-audit/'+mode+'-test-export.html',out.html);results.push({name:mode+' HTML export construction (font readiness/layout mocked)',status:'PASS'});
const player=new Window({url:'https://unit.test/',settings:{disableJavaScriptEvaluation:true,disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});
player.document.write(out.html.replace(/<script\b(?![^>]*application\/json)[^>]*>[\s\S]*?<\/script>/gi,''));
player.eval(code);const api=player.audit;api.setup();api.quiet();
assert.equal(api.mode,'player');api.state.ui.slideIndex=api.state.tutorial.slides.findIndex(s=>s.annotations.some(x=>x.id==='image-0'));
for(const type of ['image','gif','shape','text','slide-intro','callout','markup','cover','blur','magnifier','clip-frame','link','video','audio']) {
 const x=api.currentSlide().annotations.find(x=>x.type===type);const content=api.renderAnnotation(x);
 assert(content.includes('annotation-'+type));assert(!content.includes('contenteditable="true"'));
 results.push({name:mode+' exported '+type+' renderer (DOM only)',status:'PASS'});
}
await player.happyDOM.close();}catch(e){results.push({name:mode+' HTML export construction',status:'FAIL',error:e.stack});}}
fs.writeFileSync('/private/tmp/mh-toolbar-audit/new-results.json',JSON.stringify(results,null,2));
console.log(JSON.stringify({passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length,failures:results.filter(x=>x.status==='FAIL')},null,2));
await window.happyDOM.close();process.exit(results.some(x=>x.status==='FAIL')?1:0);
