#!/usr/bin/env ruby
# frozen_string_literal: true
require 'fileutils'
require 'open3'
require 'tmpdir'
require_relative 'media-publication-policy'

root = File.expand_path('..', __dir__)
Dir.chdir(root)
manifest = MediaPublication.manifest(root)
listed, error, status = Open3.capture3('git', 'ls-files', '-z')
abort(error) unless status.success?
paths = listed.split("\0").select { |path| MediaPublication.public_path?(path, manifest) && (File.exist?(path) || File.symlink?(path)) }.sort
required = manifest['public_pages'] + manifest['public_files']
missing = required - paths
abort "Required public files are not tracked: #{missing.join(', ')}" unless missing.empty?
abort 'Refusing an empty media build.' if paths.empty?
paths.each { |path| MediaPublication.validate_file!(root, path) }

# Validate every input before replacing the previous generated output.
output = File.join(root, '.media-public')
abort 'Generated output must not be a symbolic link.' if File.symlink?(output)
marker = File.join(output, '.media-generated')
abort 'Refusing to replace an unrecognized output folder.' if File.exist?(output) && !File.file?(marker)
temporary = Dir.mktmpdir('.media-build-', root)
begin
  paths.each do |path|
    target = File.join(temporary, path)
    FileUtils.mkdir_p(File.dirname(target))
    FileUtils.cp(File.join(root, path), target)
  end
  File.write(File.join(temporary, '.media-generated'), "Generated by scripts/build-media-site.rb\n")
  FileUtils.remove_entry(output) if File.directory?(output)
  File.rename(temporary, output)
ensure
  FileUtils.remove_entry(temporary) if File.directory?(temporary)
end
puts "Verified public output: #{paths.length} files in .media-public."
puts 'Builder apps, drafts, history, working exports, scripts for local tooling and test artifacts are excluded.'
